import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "@/tanstack/tanstack.provider";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider, hasLocale, useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import LangSwitcher from "@/lib/LangSwitcher";
import ThemeToggle from "@/lib/ThemeToggle";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "AK",
  description: "Generated by create next app",
};

async function IntlProviderWrapper({
  locale,
  children,
}: {
  locale: string;
  children?: React.ReactNode;
}) {
  const messagesModule = await import(`../../../messages/${locale}.json`);
  const messages = messagesModule.default;

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      {children}
    </NextIntlClientProvider>
  );
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = useLocale();

  if (!locale || !hasLocale(routing.locales, locale)) {
    notFound();
  }
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "light";

  return (
    <html lang={locale} data-theme={theme}>
      <body>
        <Toaster />
        <IntlProviderWrapper locale={locale}>
          <TanstackQueryProvider>
            <div className="flex justify-end gap-4 p-4">
              <LangSwitcher />
              <ThemeToggle />
            </div>
            {children}
          </TanstackQueryProvider>
        </IntlProviderWrapper>
      </body>
    </html>
  );
}
